spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: harsh
  jpa:
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp